# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: py3.6 tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-20.04
    defaults:
      run:
        shell: bash

    steps:
    - uses: actions/checkout@v3
    - uses: FedericoCarboni/setup-ffmpeg@v2
    - uses: clonedSemicolon/setup-strace@v8
    - name: Set up Python 3.6
      uses: actions/setup-python@v3
      with:
        python-version: "3.6.13"
        architecture: "x64"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade setuptools
        pip install flake8 pytest black pytest-cov
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install simba-uw-tf-dev --no-deps
    - name: Install ffmpeg
      id: setup-ffmpeg
      run: ffmpeg -version
    - name: Test with pytest
      run: |
        pytest -cov

    - name: Upload strace logs
      uses: actions/upload-artifact@v4
      with:
        name: strace_logs
        path: strace_logs
